Update jQuery to 3.5.0
magefile/mage pull request #458
Opened 2023-02-21 05:50 UTC by karistom

Updated jQuery to 3.5.0 to address the following issue.
https://github.com/magefile/mage/issues/431

2023-02-23 15:44 UTC, perrito666 commented
Hey, thank you for proposing this fix. The new jquery version seems to be the regular version despite its name indicating it is the minified version. We should use that version instead.

2023-02-23 15:45 UTC, perrito666 requested changes
Please replace `site/themes/learn/static/js/jquery-3.5.0.min.js` with the actual minified version of it.

2023-02-23 23:53 UTC, karistom commented
@perrito666 the file has been updated.

2023-02-24 11:59 UTC, perrito666 approved these changes

2023-02-26 23:04 UTC, karistom commented
@perrito666 @natefinch would you please review and merge the PR? Thanks.

2023-02-26 23:22 UTC, merged

2025-02-06 01:04 UTC, 1atAlcone commented
> Updated jQuery to 3.5.0 to address the following issue.
> https://github.com/magefile/mage/issues/431
> Whitesource vulnerability scan was run on the project. It showed mage having [CVE-2020-11023](https://github.com/advisories/GHSA-jpcq-cgw6-v4j6) issue. This PR will fix the issue.